config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "**/Dockerfile*"
    - "Jenkinsfile"
    - "**/*.md"
    - "**/*.py"
    - "**/*.txt"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.toml"
    - "**/*.rst"
    - "Makefile"
    - "**/*.xml"
    - "**/*.scala"
    - "**/*.sh"
    - "benchmark.yml"
    - "**/*.json"